# Carga de Datos a Traves de un read_cvs

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("../Downloads/datasets/titanic.csv.csv")

In [5]:
data.info

<bound method DataFrame.info of                                Region                Country        Item Type  \
0               Australia and Oceania                 Tuvalu        Baby Food
1   Central America and the Caribbean                Grenada           Cereal
2                              Europe                 Russia  Office Supplies
3                  Sub-Saharan Africa  Sao Tome and Principe           Fruits
4                  Sub-Saharan Africa                 Rwanda  Office Supplies
..                                ...                    ...              ...
95                 Sub-Saharan Africa                   Mali          Clothes
96                               Asia               Malaysia           Fruits
97                 Sub-Saharan Africa           Sierra Leone       Vegetables
98                      North America                 Mexico    Personal Care
99                 Sub-Saharan Africa             Mozambique        Household

   Sales Channel Order Priority  Order Date   Order ID   Ship Date  \
0        Offline              H   5/28/2010  669165933   6/27/2010
1         Online              C   8/22/2012  963881480   9/15/2012
2        Offline              L    5/2/2014  341417157    5/8/2014
3         Online              C   6/20/2014  514321792    7/5/2014
4        Offline              L    2/1/2013  115456712    2/6/2013
..           ...            ...         ...        ...         ...
95        Online              M   7/26/2011  512878119    9/3/2011
96       Offline              L  11/11/2011  810711038  12/28/2011
97       Offline              C    6/1/2016  728815257   6/29/2016
98       Offline              M   7/30/2015  559427106    8/8/2015
99       Offline              L   2/10/2012  665095412   2/15/2012

    Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  Total Profit
0         9925      255.28     159.42     2533654.00  1582243.50     951410.50
1         2804      205.70     117.11      576782.80   328376.44     248406.36
2         1779      651.21     524.96     1158502.59   933903.84     224598.75
3         8102        9.33       6.92       75591.66    56065.84      19525.82
4         5062      651.21     524.96     3296425.02  2657347.52     639077.50
..         ...         ...        ...            ...         ...           ...
95         888      109.28      35.84       97040.64    31825.92      65214.72
96        6267        9.33       6.92       58471.11    43367.64      15103.47
97        1485      154.06      90.93      228779.10   135031.05      93748.05
98        5767       81.73      56.67      471336.91   326815.89     144521.02
99        5367      668.27     502.54     3586605.09  2697132.18     889472.91

[100 rows x 14 columns]>

# EJEMPLO DE PARAMETROS DE LA FUNCION READ CVS
read.csv(filepath="/Users/frias/Downloads/datasets/titanic.csv.csv",sep=",",dtipe=None)

In [6]:
data.columns.to_list()

['Region',
 'Country',
 'Item Type',
 'Sales Channel',
 'Order Priority',
 'Order Date',
 'Order ID',
 'Ship Date',
 'Units Sold',
 'Unit Price',
 'Unit Cost',
 'Total Revenue',
 'Total Cost',
 'Total Profit']

In [7]:
media_url = 'https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv'

In [8]:
medals_data = pd.read_csv(media_url)

######

In [9]:
medals_data.head()

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

In [10]:
import urllib3
http = urllib3.PoolManager()
r = http.request('GET', media_url)
r.status
response = r.data

#defocdificandolo
str_data = response.decode('utf-8')

#se divide el tring en un aaray de filas separandolos por intros
lines = str_data.split(",")

cols_name = lines[0].split(",")
n_cols = len(cols_name)


#se genera un diccionario donde estara la informacion

counter = 0
main_dict = {}
for col in cols_name:
    main_dict[col] = []
    
#procesamos fila a fila la informacion para ir rellenando el diccioanrio
for line in lines:
    if(counter > 0):
        values = line.strip().split(",") 
        for i in range(len(cols_name)):
            main_dict[cols_name[i]].append(values[i])
       
    counter += 1
    
print("El data set tiene %d filas y %d columnas"%(counter,n_cols))

medals_df = pd.DataFrame(main_dict)
medals_data.head()

El data set tiene 8598 filas y 1 columnas

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

# resumen de datos

In [11]:
data.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50

In [12]:
data.shape

(100, 14)

In [13]:
data.tail()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91

In [14]:
data.columns.tolist()

['Region',
 'Country',
 'Item Type',
 'Sales Channel',
 'Order Priority',
 'Order Date',
 'Order ID',
 'Ship Date',
 'Units Sold',
 'Unit Price',
 'Unit Cost',
 'Total Revenue',
 'Total Cost',
 'Total Profit']

In [15]:
data.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1.000000e+02,100.000000,100.000000,100.000000,1.000000e+02,1.000000e+02,1.000000e+02
mean,5.550204e+08,5128.710000,276.761300,191.048000,1.373488e+06,9.318057e+05,4.416820e+05
std,2.606153e+08,2794.484562,235.592241,188.208181,1.460029e+06,1.083938e+06,4.385379e+05
min,1.146066e+08,124.000000,9.330000,6.920000,4.870260e+03,3.612240e+03,1.258020e+03
25%,3.389225e+08,2836.250000,81.730000,35.840000,2.687212e+05,1.688680e+05,1.214436e+05
50%,5.577086e+08,5382.500000,179.880000,107.275000,7.523144e+05,3.635664e+05,2.907680e+05
75%,7.907551e+08,7369.000000,437.200000,263.330000,2.212045e+06,1.613870e+06,6.358288e+05
max,9.940222e+08,9925.000000,668.270000,524.960000,5.997055e+06,4.509794e+06,1.719922e+06

# Missing Values

In [16]:
data.info

<bound method DataFrame.info of                                Region                Country        Item Type  \
0               Australia and Oceania                 Tuvalu        Baby Food
1   Central America and the Caribbean                Grenada           Cereal
2                              Europe                 Russia  Office Supplies
3                  Sub-Saharan Africa  Sao Tome and Principe           Fruits
4                  Sub-Saharan Africa                 Rwanda  Office Supplies
..                                ...                    ...              ...
95                 Sub-Saharan Africa                   Mali          Clothes
96                               Asia               Malaysia           Fruits
97                 Sub-Saharan Africa           Sierra Leone       Vegetables
98                      North America                 Mexico    Personal Care
99                 Sub-Saharan Africa             Mozambique        Household

   Sales Channel Order Priority  Order Date   Order ID   Ship Date  \
0        Offline              H   5/28/2010  669165933   6/27/2010
1         Online              C   8/22/2012  963881480   9/15/2012
2        Offline              L    5/2/2014  341417157    5/8/2014
3         Online              C   6/20/2014  514321792    7/5/2014
4        Offline              L    2/1/2013  115456712    2/6/2013
..           ...            ...         ...        ...         ...
95        Online              M   7/26/2011  512878119    9/3/2011
96       Offline              L  11/11/2011  810711038  12/28/2011
97       Offline              C    6/1/2016  728815257   6/29/2016
98       Offline              M   7/30/2015  559427106    8/8/2015
99       Offline              L   2/10/2012  665095412   2/15/2012

    Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  Total Profit
0         9925      255.28     159.42     2533654.00  1582243.50     951410.50
1         2804      205.70     117.11      576782.80   328376.44     248406.36
2         1779      651.21     524.96     1158502.59   933903.84     224598.75
3         8102        9.33       6.92       75591.66    56065.84      19525.82
4         5062      651.21     524.96     3296425.02  2657347.52     639077.50
..         ...         ...        ...            ...         ...           ...
95         888      109.28      35.84       97040.64    31825.92      65214.72
96        6267        9.33       6.92       58471.11    43367.64      15103.47
97        1485      154.06      90.93      228779.10   135031.05      93748.05
98        5767       81.73      56.67      471336.91   326815.89     144521.02
99        5367      668.27     502.54     3586605.09  2697132.18     889472.91

[100 rows x 14 columns]>

In [17]:
pd.isnull(data["Total Cost"]).values.ravel().sum()

0

In [18]:
pd.notnull(data["Total Cost"]).values.ravel()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [19]:
pd.notnull(data["Total Cost"]).values.ravel().sum()

100

In [20]:
data.dropna(axis=0, how="all")

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91

# Variables Dummy

In [21]:
data["Order Priority"]

0     H
1     C
2     L
3     C
4     L
     ..
95    M
96    L
97    C
98    M
99    L
Name: Order Priority, Length: 100, dtype: object

In [22]:
dumies_order = pd.get_dummies(data["Order Priority"],prefix="order")

In [23]:
dumies_order.head()

   order_C  order_H  order_L  order_M
0        0        1        0        0
1        1        0        0        0
2        0        0        1        0
3        1        0        0        0
4        0        0        1        0

In [24]:
column_name = data.columns.values.tolist()
column_name

['Region',
 'Country',
 'Item Type',
 'Sales Channel',
 'Order Priority',
 'Order Date',
 'Order ID',
 'Ship Date',
 'Units Sold',
 'Unit Price',
 'Unit Cost',
 'Total Revenue',
 'Total Cost',
 'Total Profit']

In [25]:
data = data.drop(["Order Priority"],axis =1)

In [26]:
pd.concat([data,dumies_order], axis =1 )

,Region,Country,Item Type,Sales Channel,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,order_C,order_H,order_L,order_M
0,Australia and Oceania,Tuvalu,Baby Food,Offline,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50,0,1,0,0
1,Central America and the Caribbean,Grenada,Cereal,Online,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36,1,0,0,0
2,Europe,Russia,Office Supplies,Offline,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75,0,0,1,0
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82,1,0,0,0
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sub-Saharan Africa,Mali,Clothes,Online,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72,0,0,0,1
96,Asia,Malaysia,Fruits,Offline,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47,0,0,1,0
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05,1,0,0,0
98,North America,Mexico,Personal Care,Offline,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02,0,0,0,1
99,Sub-Saharan Africa,Mozambique,Household,Offline,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91,0,0,1,0

In [27]:
def createdummies(df,var_name):
    dummy = pd.get_dummies(df[var_name], prefix=var_name)
    df = data.drop([var_name],axis = 1)
    df = pd.concat([df,dummy], axis = 1)
    return df

In [28]:
createdummies(data,"Item Type")

,Region,Country,Sales Channel,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,...,Item Type_Cereal,Item Type_Clothes,Item Type_Cosmetics,Item Type_Fruits,Item Type_Household,Item Type_Meat,Item Type_Office Supplies,Item Type_Personal Care,Item Type_Snacks,Item Type_Vegetables
0,Australia and Oceania,Tuvalu,Offline,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,...,0,0,0,0,0,0,0,0,0,0
1,Central America and the Caribbean,Grenada,Online,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,...,1,0,0,0,0,0,0,0,0,0
2,Europe,Russia,Offline,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,...,0,0,0,0,0,0,1,0,0,0
3,Sub-Saharan Africa,Sao Tome and Principe,Online,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,...,0,0,0,1,0,0,0,0,0,0
4,Sub-Saharan Africa,Rwanda,Offline,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sub-Saharan Africa,Mali,Online,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,...,0,1,0,0,0,0,0,0,0,0
96,Asia,Malaysia,Offline,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,...,0,0,0,1,0,0,0,0,0,0
97,Sub-Saharan Africa,Sierra Leone,Offline,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,...,0,0,0,0,0,0,0,0,0,1
98,North America,Mexico,Offline,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,...,0,0,0,0,0,0,0,1,0,0
99,Sub-Saharan Africa,Mozambique,Offline,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,...,0,0,0,0,1,0,0,0,0,0

# OPERACIONES DE MANEJOS DE DATOS

In [29]:
import pandas as pd

In [30]:
data1 = pd.read_excel('Reporte.xlsx')

In [31]:
data1.info

<bound method DataFrame.info of     Código de Producto  Partida Arancelaria  \
0     RP20201000000730             21061000
1     RP202104000000E1             64029990
2     RP202106000007C0             39269099
3       201807000002F3             87031000
4     RP202101000003D4             76169990
..                 ...                  ...
195          P11061358             32041400
196          P11061359             32041400
197          P11061360             32041400
198          P11061361             32041400
199          P11061362             32041400

                                    Nombre de Producto  Cod. Marca  Marca  \
0                                 PROTEINA CONCENTRADA    2008MI31  SOLAE
1                                TENIS PARA CABALLEROS  0604MC1002     CL
2    PUNTA DE FILTRO CONDUCTIVO PRE ESTRELIZADOS DE...  2505MC1001   NEST
3                                        CARRO DE GOLF  B002260312   EZGO
4           MINI SOPORTE DE TUBERIA MINI TRUSS BRACKET  201811028F   SONY
..                                                 ...         ...    ...
195                            TUBANTIN GRAY CGLL CONC   B11050038    NaN
196                                 TUBANTIN GREEN 5GL   B11050038    NaN
197                              TUBANTIN GREEN BL H.C   B11050038    NaN
198                          TUBANTIN ORANGE GGLN 200%   B11050038    NaN
199                                   TUBANTIN PINK 2B   B11050038    NaN

       Cod. Modelo              Modelo      Unidad                  País  \
0           20MI47          SUPRO EX45  Kilogramos        ESTADOS UNIDOS
1       0406MC1002           NO APLICA         Par                 CHINA
2       0525MC1001           NO APLICA    Unidades                 CHINA
3    20181307J0105  CUSHMAN HAULER PRO    Unidades        ESTADOS UNIDOS
4          1312J01           No Aplica    Unidades               TURQUÍA
..             ...                 ...         ...                   ...
195      M11060065                 NaN  Kilogramos  REPÚBLICA DOMINICANA
196      M11060065                 NaN  Kilogramos  REPÚBLICA DOMINICANA
197      M11060065                 NaN  Kilogramos  REPÚBLICA DOMINICANA
198      M11060065                 NaN  Kilogramos  REPÚBLICA DOMINICANA
199      M11060065                 NaN  Kilogramos  REPÚBLICA DOMINICANA

                                      Especificaciones  \
0                          PRESENTACIONUNITARIA: 20 ||
1    MATERIALSUPERIOR:  PLASTICO || SUELA:  PLASTIC...
2                               unidadesxempaque: 1 ||
3    kilowattsmotor: 1 || SERIE: NO APLICA || COMBU...
4                                                  NaN
..                                                 ...
195                                                NaN
196                                                NaN
197                                                NaN
198                                                NaN
199                                                NaN

                         Régimen  Estado
0    PARA VENTA AL MERCADO LOCAL  Activo
1    PARA VENTA AL MERCADO LOCAL  Activo
2              ADMISIÓN TEMPORAL  Activo
3    PARA VENTA AL MERCADO LOCAL  Activo
4    PARA VENTA AL MERCADO LOCAL  Activo
..                           ...     ...
195  PARA VENTA AL MERCADO LOCAL  Activo
196  PARA VENTA AL MERCADO LOCAL  Activo
197  PARA VENTA AL MERCADO LOCAL  Activo
198  PARA VENTA AL MERCADO LOCAL  Activo
199  PARA VENTA AL MERCADO LOCAL  Activo

[200 rows x 12 columns]>

In [32]:
data1.head()

,Código de Producto,Partida Arancelaria,Nombre de Producto,Cod. Marca,Marca,Cod. Modelo,Modelo,Unidad,País,Especificaciones,Régimen,Estado
0,RP20201000000730,21061000,PROTEINA CONCENTRADA,2008MI31,SOLAE,20MI47,SUPRO EX45,Kilogramos,ESTADOS UNIDOS,PRESENTACIONUNITARIA: 20 ||,PARA VENTA AL MERCADO LOCAL,Activo
1,RP202104000000E1,64029990,TENIS PARA CABALLEROS,0604MC1002,CL,0406MC1002,NO APLICA,Par,CHINA,MATERIALSUPERIOR: PLASTICO || SUELA: PLASTIC...,PARA VENTA AL MERCADO LOCAL,Activo
2,RP202106000007C0,39269099,PUNTA DE FILTRO CONDUCTIVO PRE ESTRELIZADOS DE...,2505MC1001,NEST,0525MC1001,NO APLICA,Unidades,CHINA,unidadesxempaque: 1 ||,ADMISIÓN TEMPORAL,Activo
3,201807000002F3,87031000,CARRO DE GOLF,B002260312,EZGO,20181307J0105,CUSHMAN HAULER PRO,Unidades,ESTADOS UNIDOS,kilowattsmotor: 1 || SERIE: NO APLICA || COMBU...,PARA VENTA AL MERCADO LOCAL,Activo
4,RP202101000003D4,76169990,MINI SOPORTE DE TUBERIA MINI TRUSS BRACKET,201811028F,SONY,1312J01,No Aplica,Unidades,TURQUÍA,NaN,PARA VENTA AL MERCADO LOCAL,Activo

In [33]:
data1.dropna().head(100)

,Código de Producto,Partida Arancelaria,Nombre de Producto,Cod. Marca,Marca,Cod. Modelo,Modelo,Unidad,País,Especificaciones,Régimen,Estado
0,RP20201000000730,21061000,PROTEINA CONCENTRADA,2008MI31,SOLAE,20MI47,SUPRO EX45,Kilogramos,ESTADOS UNIDOS,PRESENTACIONUNITARIA: 20 ||,PARA VENTA AL MERCADO LOCAL,Activo
1,RP202104000000E1,64029990,TENIS PARA CABALLEROS,0604MC1002,CL,0406MC1002,NO APLICA,Par,CHINA,MATERIALSUPERIOR: PLASTICO || SUELA: PLASTIC...,PARA VENTA AL MERCADO LOCAL,Activo
2,RP202106000007C0,39269099,PUNTA DE FILTRO CONDUCTIVO PRE ESTRELIZADOS DE...,2505MC1001,NEST,0525MC1001,NO APLICA,Unidades,CHINA,unidadesxempaque: 1 ||,ADMISIÓN TEMPORAL,Activo
3,201807000002F3,87031000,CARRO DE GOLF,B002260312,EZGO,20181307J0105,CUSHMAN HAULER PRO,Unidades,ESTADOS UNIDOS,kilowattsmotor: 1 || SERIE: NO APLICA || COMBU...,PARA VENTA AL MERCADO LOCAL,Activo
8,RP20200600000637,21069092,SUPLEMENTO NUTRICIONAL EN CAPSULA,2006DV32,THERASCIENCE,20DV10,CETOLIKE MCT OIL,Litros,ESTADOS UNIDOS,PRESENTACION: 500 ML || SABOR: NO APLICA ||,PARA VENTA AL MERCADO LOCAL,Activo
20,RP201810000000AD,22042100,VINO,2018100201DV,CHATEAU CANTIN,201810020102DV,SAINT EMILION GRAND CRU 16,Litros,FRANCIA,GRADOALCOHOL: 14.50 || UNIDADXCAJA: 6 || PRESE...,PARA VENTA AL MERCADO LOCAL,Activo
21,RP2018100000030C,87032499,AUTOMOVIL,B09110016,Mercedes Benz,M001071117,S560,Unidades,ALEMANIA,SERIE: NO APLICA || COMBUSTIBLE: GASOLINA || C...,PARA VENTA AL MERCADO LOCAL,Activo
22,20180600000DCA,22042100,VINO,201806220102,VERBO,2018062201C,AGLIANICO DEL VULTURE,Litros,ITALIA,GRADOALCOHOL: 14.00 || UNIDADXCAJA: 6 || PRESE...,PARA VENTA AL MERCADO LOCAL,Activo
23,201708000006C4,22087020,LICOR,2018092001DF,BROGANS,2018092002DF,IRISH CREAM,Litros,IRLANDA,GRADOALCOHOL: 40.00 || UNIDADXCAJA: 12 || PRES...,PARA VENTA AL MERCADO LOCAL,Activo
24,RP201903000006DB,21069092,SUPLEMENTO NUTRICIONAL EN CAPSULA,1903MC01,LIFE EXTENSION,19MC88,SUPER ABSORBABLE COQ10,Unidades,ESTADOS UNIDOS,PRESENTACION: 60UNIDADES || SABOR: NO APLICA ||,PARA VENTA AL MERCADO LOCAL,Activo
25,RP2019030000071E,21069092,SUPLEMENTO NUTRICIONAL EN CAPSULA,1903MC01,LIFE EXTENSION,19MC125,LIFE EXTENSION MIX 360,Unidades,ESTADOS UNIDOS,PRESENTACION: 360UNIDADES || SABOR: NO APLICA ||,PARA VENTA AL MERCADO LOCAL,Activo
26,RP201903000009E0,69072310,BALDOSAS ESMALTADAS,201903MC831,KERAMEX,MC20191803435,CUBIC SQUARE PERLA,Unidades,ESPAÑA,COEFICIENTEABSORCIONAGUA: MAYOR DE 10% || MEDI...,PARA VENTA AL MERCADO LOCAL,Activo
27,RP20190400000475,22030000,CERVEZA,4041J,DELIRIUM,2018100102F,NOCTURNUM,Litros,REPÚBLICA CHECA,GRADOALCOHOL: 8.50 || GRADOALCOHOL: 24 || PRES...,PARA VENTA AL MERCADO LOCAL,Activo
28,RP20190400000452,69072210,BALDOSAS ESMALTADAS,201903MC884,EMBRAMACO,MC1534002,52913 TREVOR TEX,Metros Cuadrados,BRASIL,COEFICIENTEABSORCIONAGUA: 5% - 10% || MEDIDA: ...,PARA VENTA AL MERCADO LOCAL,Activo
33,RP20190700000244,69072210,BALDOSAS SIN ESMALTAR,201903MC905,PAMESA,19JR86,RELIEVE,Metros Cuadrados,ESPAÑA,COEFICIENTEABSORCIONAGUA: 3% A 6% || MEDIDA: 3...,PARA VENTA AL MERCADO LOCAL,Activo
34,RP201906000001F9,87054000,CAMION HORMIGO SERIE:GRANITE 500 || COMBUSTIBL...,MACK,MACK,M002080816,CV513,Unidades,ESTADOS UNIDOS,CAMION HORMIGO SERIE:GRANITE 500 || COMBUSTIBL...,PARA VENTA AL MERCADO LOCAL,Activo
35,RP2019040000074E,69072210,BALDOSAS ESMALTADAS,201903MC876,FORMIGRES,MC240444,JAVA MARROM,Unidades,BRASIL,COEFICIENTEABSORCIONAGUA: 6 A 10% || MEDIDA: 4...,PARA VENTA AL MERCADO LOCAL,Activo
36,RP201905000005B9,69072190,PORCELANATOS,201903MC1035,VARMORA,1905MC200,APPOLO,Metros Cuadrados,INDIA,"COEFICIENTEABSORCIONAGUA: 0,08% || MEDIDA: 60 ...",PARA VENTA AL MERCADO LOCAL,Activo
37,2017080000081A,22042100,VINO,202,Santa Carolina,2017-349,Reserva Carmenere,Litros,CHILE,GRADOALCOHOL: 12 || unidadesxcaja: 12 || PRESE...,PARA VENTA AL MERCADO LOCAL,Activo
38,2017100000023C,22042100,VINO,984D,COPPOLA,2017-4087,COPPOLA DIRECTORS CUT CINEMA BLEND,Litros,ESTADOS UNIDOS,GRADOALCOHOL: 14.5 || unidadesxcaja: 12 || PRE...,PARA VENTA AL MERCADO LOCAL,Activo
39,2017090000017D,22042100,VINO,512,RAMOS PINTO,2017-1610,TAWNY PORT,Litros,PORTUGAL,GRADOALCOHOL: 20 || unidadesxcaja: 6 || PRESEN...,PARA VENTA AL MERCADO LOCAL,Activo
40,20171000000622,22042100,VINO,6T,CHIANTARI NERO AVOLA,2017-7T,TINTO,Litros,ITALIA,GRADOALCOHOL: 13.5 || unidadesxcaja: 6 || PRES...,PARA VENTA AL MERCADO LOCAL,Activo
41,20170800000C3E,22042100,VINO,430,TWINS,2017-1257,MEYNEY 2014,Litros,FRANCIA,GRADOALCOHOL: 13 || unidadesxcaja: 12 || PRESE...,PARA VENTA AL MERCADO LOCAL,Activo
42,2017080000080D,22086000,VODKA,137,Ketel One,2017-617,Ketel One Vodka,Litros,PAÍSES BAJOS,GRADOALCOHOL: 40 || UNIDADXCAJA: 6 || PRESENTA...,PARA VENTA AL MERCADO LOCAL,Activo
44,201712000004A5,22084011,RON,3696J,HAVANA CLUB,2017-36961,AÑEJO RESERVA,Litros,CUBA,GRADOALCOHOL: 40 || UNIDADXCAJA: 12 || PRESENT...,PARA VENTA AL MERCADO LOCAL,Activo
45,20180600000327,87032399,AUTOMOVIL,B09110013,Lexus,20180706,GS 200T,Unidades,JAPÓN,SERIE: NO APLICA || COMBUSTIBLE: GASOLINA || C...,PARA VENTA AL MERCADO LOCAL,Activo

In [34]:
data1.info

<bound method DataFrame.info of     Código de Producto  Partida Arancelaria  \
0     RP20201000000730             21061000
1     RP202104000000E1             64029990
2     RP202106000007C0             39269099
3       201807000002F3             87031000
4     RP202101000003D4             76169990
..                 ...                  ...
195          P11061358             32041400
196          P11061359             32041400
197          P11061360             32041400
198          P11061361             32041400
199          P11061362             32041400

                                    Nombre de Producto  Cod. Marca  Marca  \
0                                 PROTEINA CONCENTRADA    2008MI31  SOLAE
1                                TENIS PARA CABALLEROS  0604MC1002     CL
2    PUNTA DE FILTRO CONDUCTIVO PRE ESTRELIZADOS DE...  2505MC1001   NEST
3                                        CARRO DE GOLF  B002260312   EZGO
4           MINI SOPORTE DE TUBERIA MINI TRUSS BRACKET  201811028F   SONY
..                                                 ...         ...    ...
195                            TUBANTIN GRAY CGLL CONC   B11050038    NaN
196                                 TUBANTIN GREEN 5GL   B11050038    NaN
197                              TUBANTIN GREEN BL H.C   B11050038    NaN
198                          TUBANTIN ORANGE GGLN 200%   B11050038    NaN
199                                   TUBANTIN PINK 2B   B11050038    NaN

       Cod. Modelo              Modelo      Unidad                  País  \
0           20MI47          SUPRO EX45  Kilogramos        ESTADOS UNIDOS
1       0406MC1002           NO APLICA         Par                 CHINA
2       0525MC1001           NO APLICA    Unidades                 CHINA
3    20181307J0105  CUSHMAN HAULER PRO    Unidades        ESTADOS UNIDOS
4          1312J01           No Aplica    Unidades               TURQUÍA
..             ...                 ...         ...                   ...
195      M11060065                 NaN  Kilogramos  REPÚBLICA DOMINICANA
196      M11060065                 NaN  Kilogramos  REPÚBLICA DOMINICANA
197      M11060065                 NaN  Kilogramos  REPÚBLICA DOMINICANA
198      M11060065                 NaN  Kilogramos  REPÚBLICA DOMINICANA
199      M11060065                 NaN  Kilogramos  REPÚBLICA DOMINICANA

                                      Especificaciones  \
0                          PRESENTACIONUNITARIA: 20 ||
1    MATERIALSUPERIOR:  PLASTICO || SUELA:  PLASTIC...
2                               unidadesxempaque: 1 ||
3    kilowattsmotor: 1 || SERIE: NO APLICA || COMBU...
4                                                  NaN
..                                                 ...
195                                                NaN
196                                                NaN
197                                                NaN
198                                                NaN
199                                                NaN

                         Régimen  Estado
0    PARA VENTA AL MERCADO LOCAL  Activo
1    PARA VENTA AL MERCADO LOCAL  Activo
2              ADMISIÓN TEMPORAL  Activo
3    PARA VENTA AL MERCADO LOCAL  Activo
4    PARA VENTA AL MERCADO LOCAL  Activo
..                           ...     ...
195  PARA VENTA AL MERCADO LOCAL  Activo
196  PARA VENTA AL MERCADO LOCAL  Activo
197  PARA VENTA AL MERCADO LOCAL  Activo
198  PARA VENTA AL MERCADO LOCAL  Activo
199  PARA VENTA AL MERCADO LOCAL  Activo

[200 rows x 12 columns]>

In [35]:
data2 = data1

In [36]:
data2.dropna(axis=0,how="any")

,Código de Producto,Partida Arancelaria,Nombre de Producto,Cod. Marca,Marca,Cod. Modelo,Modelo,Unidad,País,Especificaciones,Régimen,Estado
0,RP20201000000730,21061000,PROTEINA CONCENTRADA,2008MI31,SOLAE,20MI47,SUPRO EX45,Kilogramos,ESTADOS UNIDOS,PRESENTACIONUNITARIA: 20 ||,PARA VENTA AL MERCADO LOCAL,Activo
1,RP202104000000E1,64029990,TENIS PARA CABALLEROS,0604MC1002,CL,0406MC1002,NO APLICA,Par,CHINA,MATERIALSUPERIOR: PLASTICO || SUELA: PLASTIC...,PARA VENTA AL MERCADO LOCAL,Activo
2,RP202106000007C0,39269099,PUNTA DE FILTRO CONDUCTIVO PRE ESTRELIZADOS DE...,2505MC1001,NEST,0525MC1001,NO APLICA,Unidades,CHINA,unidadesxempaque: 1 ||,ADMISIÓN TEMPORAL,Activo
3,201807000002F3,87031000,CARRO DE GOLF,B002260312,EZGO,20181307J0105,CUSHMAN HAULER PRO,Unidades,ESTADOS UNIDOS,kilowattsmotor: 1 || SERIE: NO APLICA || COMBU...,PARA VENTA AL MERCADO LOCAL,Activo
8,RP20200600000637,21069092,SUPLEMENTO NUTRICIONAL EN CAPSULA,2006DV32,THERASCIENCE,20DV10,CETOLIKE MCT OIL,Litros,ESTADOS UNIDOS,PRESENTACION: 500 ML || SABOR: NO APLICA ||,PARA VENTA AL MERCADO LOCAL,Activo
20,RP201810000000AD,22042100,VINO,2018100201DV,CHATEAU CANTIN,201810020102DV,SAINT EMILION GRAND CRU 16,Litros,FRANCIA,GRADOALCOHOL: 14.50 || UNIDADXCAJA: 6 || PRESE...,PARA VENTA AL MERCADO LOCAL,Activo
21,RP2018100000030C,87032499,AUTOMOVIL,B09110016,Mercedes Benz,M001071117,S560,Unidades,ALEMANIA,SERIE: NO APLICA || COMBUSTIBLE: GASOLINA || C...,PARA VENTA AL MERCADO LOCAL,Activo
22,20180600000DCA,22042100,VINO,201806220102,VERBO,2018062201C,AGLIANICO DEL VULTURE,Litros,ITALIA,GRADOALCOHOL: 14.00 || UNIDADXCAJA: 6 || PRESE...,PARA VENTA AL MERCADO LOCAL,Activo
23,201708000006C4,22087020,LICOR,2018092001DF,BROGANS,2018092002DF,IRISH CREAM,Litros,IRLANDA,GRADOALCOHOL: 40.00 || UNIDADXCAJA: 12 || PRES...,PARA VENTA AL MERCADO LOCAL,Activo
24,RP201903000006DB,21069092,SUPLEMENTO NUTRICIONAL EN CAPSULA,1903MC01,LIFE EXTENSION,19MC88,SUPER ABSORBABLE COQ10,Unidades,ESTADOS UNIDOS,PRESENTACION: 60UNIDADES || SABOR: NO APLICA ||,PARA VENTA AL MERCADO LOCAL,Activo
25,RP2019030000071E,21069092,SUPLEMENTO NUTRICIONAL EN CAPSULA,1903MC01,LIFE EXTENSION,19MC125,LIFE EXTENSION MIX 360,Unidades,ESTADOS UNIDOS,PRESENTACION: 360UNIDADES || SABOR: NO APLICA ||,PARA VENTA AL MERCADO LOCAL,Activo
26,RP201903000009E0,69072310,BALDOSAS ESMALTADAS,201903MC831,KERAMEX,MC20191803435,CUBIC SQUARE PERLA,Unidades,ESPAÑA,COEFICIENTEABSORCIONAGUA: MAYOR DE 10% || MEDI...,PARA VENTA AL MERCADO LOCAL,Activo
27,RP20190400000475,22030000,CERVEZA,4041J,DELIRIUM,2018100102F,NOCTURNUM,Litros,REPÚBLICA CHECA,GRADOALCOHOL: 8.50 || GRADOALCOHOL: 24 || PRES...,PARA VENTA AL MERCADO LOCAL,Activo
28,RP20190400000452,69072210,BALDOSAS ESMALTADAS,201903MC884,EMBRAMACO,MC1534002,52913 TREVOR TEX,Metros Cuadrados,BRASIL,COEFICIENTEABSORCIONAGUA: 5% - 10% || MEDIDA: ...,PARA VENTA AL MERCADO LOCAL,Activo
33,RP20190700000244,69072210,BALDOSAS SIN ESMALTAR,201903MC905,PAMESA,19JR86,RELIEVE,Metros Cuadrados,ESPAÑA,COEFICIENTEABSORCIONAGUA: 3% A 6% || MEDIDA: 3...,PARA VENTA AL MERCADO LOCAL,Activo
34,RP201906000001F9,87054000,CAMION HORMIGO SERIE:GRANITE 500 || COMBUSTIBL...,MACK,MACK,M002080816,CV513,Unidades,ESTADOS UNIDOS,CAMION HORMIGO SERIE:GRANITE 500 || COMBUSTIBL...,PARA VENTA AL MERCADO LOCAL,Activo
35,RP2019040000074E,69072210,BALDOSAS ESMALTADAS,201903MC876,FORMIGRES,MC240444,JAVA MARROM,Unidades,BRASIL,COEFICIENTEABSORCIONAGUA: 6 A 10% || MEDIDA: 4...,PARA VENTA AL MERCADO LOCAL,Activo
36,RP201905000005B9,69072190,PORCELANATOS,201903MC1035,VARMORA,1905MC200,APPOLO,Metros Cuadrados,INDIA,"COEFICIENTEABSORCIONAGUA: 0,08% || MEDIDA: 60 ...",PARA VENTA AL MERCADO LOCAL,Activo
37,2017080000081A,22042100,VINO,202,Santa Carolina,2017-349,Reserva Carmenere,Litros,CHILE,GRADOALCOHOL: 12 || unidadesxcaja: 12 || PRESE...,PARA VENTA AL MERCADO LOCAL,Activo
38,2017100000023C,22042100,VINO,984D,COPPOLA,2017-4087,COPPOLA DIRECTORS CUT CINEMA BLEND,Litros,ESTADOS UNIDOS,GRADOALCOHOL: 14.5 || unidadesxcaja: 12 || PRE...,PARA VENTA AL MERCADO LOCAL,Activo
39,2017090000017D,22042100,VINO,512,RAMOS PINTO,2017-1610,TAWNY PORT,Litros,PORTUGAL,GRADOALCOHOL: 20 || unidadesxcaja: 6 || PRESEN...,PARA VENTA AL MERCADO LOCAL,Activo
40,20171000000622,22042100,VINO,6T,CHIANTARI NERO AVOLA,2017-7T,TINTO,Litros,ITALIA,GRADOALCOHOL: 13.5 || unidadesxcaja: 6 || PRES...,PARA VENTA AL MERCADO LOCAL,Activo
41,20170800000C3E,22042100,VINO,430,TWINS,2017-1257,MEYNEY 2014,Litros,FRANCIA,GRADOALCOHOL: 13 || unidadesxcaja: 12 || PRESE...,PARA VENTA AL MERCADO LOCAL,Activo
42,2017080000080D,22086000,VODKA,137,Ketel One,2017-617,Ketel One Vodka,Litros,PAÍSES BAJOS,GRADOALCOHOL: 40 || UNIDADXCAJA: 6 || PRESENTA...,PARA VENTA AL MERCADO LOCAL,Activo
44,201712000004A5,22084011,RON,3696J,HAVANA CLUB,2017-36961,AÑEJO RESERVA,Litros,CUBA,GRADOALCOHOL: 40 || UNIDADXCAJA: 12 || PRESENT...,PARA VENTA AL MERCADO LOCAL,Activo
45,20180600000327,87032399,AUTOMOVIL,B09110013,Lexus,20180706,GS 200T,Unidades,JAPÓN,SERIE: NO APLICA || COMBUSTIBLE: GASOLINA || C...,PARA VENTA AL MERCADO LOCAL,Activo

Que hacer con los valores faltantes

In [37]:
data3 = data1

In [38]:
data3.fillna(0)

,Código de Producto,Partida Arancelaria,Nombre de Producto,Cod. Marca,Marca,Cod. Modelo,Modelo,Unidad,País,Especificaciones,Régimen,Estado
0,RP20201000000730,21061000,PROTEINA CONCENTRADA,2008MI31,SOLAE,20MI47,SUPRO EX45,Kilogramos,ESTADOS UNIDOS,PRESENTACIONUNITARIA: 20 ||,PARA VENTA AL MERCADO LOCAL,Activo
1,RP202104000000E1,64029990,TENIS PARA CABALLEROS,0604MC1002,CL,0406MC1002,NO APLICA,Par,CHINA,MATERIALSUPERIOR: PLASTICO || SUELA: PLASTIC...,PARA VENTA AL MERCADO LOCAL,Activo
2,RP202106000007C0,39269099,PUNTA DE FILTRO CONDUCTIVO PRE ESTRELIZADOS DE...,2505MC1001,NEST,0525MC1001,NO APLICA,Unidades,CHINA,unidadesxempaque: 1 ||,ADMISIÓN TEMPORAL,Activo
3,201807000002F3,87031000,CARRO DE GOLF,B002260312,EZGO,20181307J0105,CUSHMAN HAULER PRO,Unidades,ESTADOS UNIDOS,kilowattsmotor: 1 || SERIE: NO APLICA || COMBU...,PARA VENTA AL MERCADO LOCAL,Activo
4,RP202101000003D4,76169990,MINI SOPORTE DE TUBERIA MINI TRUSS BRACKET,201811028F,SONY,1312J01,No Aplica,Unidades,TURQUÍA,0,PARA VENTA AL MERCADO LOCAL,Activo
...,...,...,...,...,...,...,...,...,...,...,...,...
195,P11061358,32041400,TUBANTIN GRAY CGLL CONC,B11050038,0,M11060065,0,Kilogramos,REPÚBLICA DOMINICANA,0,PARA VENTA AL MERCADO LOCAL,Activo
196,P11061359,32041400,TUBANTIN GREEN 5GL,B11050038,0,M11060065,0,Kilogramos,REPÚBLICA DOMINICANA,0,PARA VENTA AL MERCADO LOCAL,Activo
197,P11061360,32041400,TUBANTIN GREEN BL H.C,B11050038,0,M11060065,0,Kilogramos,REPÚBLICA DOMINICANA,0,PARA VENTA AL MERCADO LOCAL,Activo
198,P11061361,32041400,TUBANTIN ORANGE GGLN 200%,B11050038,0,M11060065,0,Kilogramos,REPÚBLICA DOMINICANA,0,PARA VENTA AL MERCADO LOCAL,Activo
199,P11061362,32041400,TUBANTIN PINK 2B,B11050038,0,M11060065,0,Kilogramos,REPÚBLICA DOMINICANA,0,PARA VENTA AL MERCADO LOCAL,Activo

In [39]:
data3.fillna("Desconocido").tail()

,Código de Producto,Partida Arancelaria,Nombre de Producto,Cod. Marca,Marca,Cod. Modelo,Modelo,Unidad,País,Especificaciones,Régimen,Estado
195,P11061358,32041400,TUBANTIN GRAY CGLL CONC,B11050038,Desconocido,M11060065,Desconocido,Kilogramos,REPÚBLICA DOMINICANA,Desconocido,PARA VENTA AL MERCADO LOCAL,Activo
196,P11061359,32041400,TUBANTIN GREEN 5GL,B11050038,Desconocido,M11060065,Desconocido,Kilogramos,REPÚBLICA DOMINICANA,Desconocido,PARA VENTA AL MERCADO LOCAL,Activo
197,P11061360,32041400,TUBANTIN GREEN BL H.C,B11050038,Desconocido,M11060065,Desconocido,Kilogramos,REPÚBLICA DOMINICANA,Desconocido,PARA VENTA AL MERCADO LOCAL,Activo
198,P11061361,32041400,TUBANTIN ORANGE GGLN 200%,B11050038,Desconocido,M11060065,Desconocido,Kilogramos,REPÚBLICA DOMINICANA,Desconocido,PARA VENTA AL MERCADO LOCAL,Activo
199,P11061362,32041400,TUBANTIN PINK 2B,B11050038,Desconocido,M11060065,Desconocido,Kilogramos,REPÚBLICA DOMINICANA,Desconocido,PARA VENTA AL MERCADO LOCAL,Activo

# cirugia de Datos

In [40]:
datos = pd.read_excel('Reporte.xlsx')

In [41]:
datos.head()

,Código de Producto,Partida Arancelaria,Nombre de Producto,Cod. Marca,Marca,Cod. Modelo,Modelo,Unidad,País,Especificaciones,Régimen,Estado
0,RP20201000000730,21061000,PROTEINA CONCENTRADA,2008MI31,SOLAE,20MI47,SUPRO EX45,Kilogramos,ESTADOS UNIDOS,PRESENTACIONUNITARIA: 20 ||,PARA VENTA AL MERCADO LOCAL,Activo
1,RP202104000000E1,64029990,TENIS PARA CABALLEROS,0604MC1002,CL,0406MC1002,NO APLICA,Par,CHINA,MATERIALSUPERIOR: PLASTICO || SUELA: PLASTIC...,PARA VENTA AL MERCADO LOCAL,Activo
2,RP202106000007C0,39269099,PUNTA DE FILTRO CONDUCTIVO PRE ESTRELIZADOS DE...,2505MC1001,NEST,0525MC1001,NO APLICA,Unidades,CHINA,unidadesxempaque: 1 ||,ADMISIÓN TEMPORAL,Activo
3,201807000002F3,87031000,CARRO DE GOLF,B002260312,EZGO,20181307J0105,CUSHMAN HAULER PRO,Unidades,ESTADOS UNIDOS,kilowattsmotor: 1 || SERIE: NO APLICA || COMBU...,PARA VENTA AL MERCADO LOCAL,Activo
4,RP202101000003D4,76169990,MINI SOPORTE DE TUBERIA MINI TRUSS BRACKET,201811028F,SONY,1312J01,No Aplica,Unidades,TURQUÍA,NaN,PARA VENTA AL MERCADO LOCAL,Activo

### Crear subconjutos de datos

In [42]:
Marca = datos["Marca"]

In [43]:
Marca.head()

0    SOLAE
1       CL
2     NEST
3     EZGO
4     SONY
Name: Marca, dtype: object

In [44]:
subset = datos[["Marca","Modelo","Especificaciones"]]

In [45]:
subset.fillna("Desconocido").head()

,Marca,Modelo,Especificaciones
0,SOLAE,SUPRO EX45,PRESENTACIONUNITARIA: 20 ||
1,CL,NO APLICA,MATERIALSUPERIOR: PLASTICO || SUELA: PLASTIC...
2,NEST,NO APLICA,unidadesxempaque: 1 ||
3,EZGO,CUSHMAN HAULER PRO,kilowattsmotor: 1 || SERIE: NO APLICA || COMBU...
4,SONY,No Aplica,Desconocido

In [46]:
type(subset)

pandas.core.frame.DataFrame

In [47]:
data_desires = ["Marca","Modelo","Especificaciones"]
subset = datos[data_desires]
subset.fillna("Desconocido").head()

,Marca,Modelo,Especificaciones
0,SOLAE,SUPRO EX45,PRESENTACIONUNITARIA: 20 ||
1,CL,NO APLICA,MATERIALSUPERIOR: PLASTICO || SUELA: PLASTIC...
2,NEST,NO APLICA,unidadesxempaque: 1 ||
3,EZGO,CUSHMAN HAULER PRO,kilowattsmotor: 1 || SERIE: NO APLICA || COMBU...
4,SONY,No Aplica,Desconocido

In [48]:
todo = datos.columns.values.tolist()
todo

['Código de Producto',
 'Partida Arancelaria',
 'Nombre de Producto',
 'Cod. Marca',
 'Marca',
 'Cod. Modelo',
 'Modelo',
 'Unidad',
 'País',
 'Especificaciones',
 'Régimen',
 'Estado']

In [49]:
algunas = ["Marca","Modelo","Especificaciones"]
algunas

['Marca', 'Modelo', 'Especificaciones']

In [50]:
sublist = [x for x in todo if x not in data_desires]
sublist

['Código de Producto',
 'Partida Arancelaria',
 'Nombre de Producto',
 'Cod. Marca',
 'Cod. Modelo',
 'Unidad',
 'País',
 'Régimen',
 'Estado']

In [51]:
subset = datos[sublist]
subset.head()

,Código de Producto,Partida Arancelaria,Nombre de Producto,Cod. Marca,Cod. Modelo,Unidad,País,Régimen,Estado
0,RP20201000000730,21061000,PROTEINA CONCENTRADA,2008MI31,20MI47,Kilogramos,ESTADOS UNIDOS,PARA VENTA AL MERCADO LOCAL,Activo
1,RP202104000000E1,64029990,TENIS PARA CABALLEROS,0604MC1002,0406MC1002,Par,CHINA,PARA VENTA AL MERCADO LOCAL,Activo
2,RP202106000007C0,39269099,PUNTA DE FILTRO CONDUCTIVO PRE ESTRELIZADOS DE...,2505MC1001,0525MC1001,Unidades,CHINA,ADMISIÓN TEMPORAL,Activo
3,201807000002F3,87031000,CARRO DE GOLF,B002260312,20181307J0105,Unidades,ESTADOS UNIDOS,PARA VENTA AL MERCADO LOCAL,Activo
4,RP202101000003D4,76169990,MINI SOPORTE DE TUBERIA MINI TRUSS BRACKET,201811028F,1312J01,Unidades,TURQUÍA,PARA VENTA AL MERCADO LOCAL,Activo

In [53]:
datos[1:25]

,Código de Producto,Partida Arancelaria,Nombre de Producto,Cod. Marca,Marca,Cod. Modelo,Modelo,Unidad,País,Especificaciones,Régimen,Estado
1,RP202104000000E1,64029990,TENIS PARA CABALLEROS,0604MC1002,CL,0406MC1002,NO APLICA,Par,CHINA,MATERIALSUPERIOR: PLASTICO || SUELA: PLASTIC...,PARA VENTA AL MERCADO LOCAL,Activo
2,RP202106000007C0,39269099,PUNTA DE FILTRO CONDUCTIVO PRE ESTRELIZADOS DE...,2505MC1001,NEST,0525MC1001,NO APLICA,Unidades,CHINA,unidadesxempaque: 1 ||,ADMISIÓN TEMPORAL,Activo
3,201807000002F3,87031000,CARRO DE GOLF,B002260312,EZGO,20181307J0105,CUSHMAN HAULER PRO,Unidades,ESTADOS UNIDOS,kilowattsmotor: 1 || SERIE: NO APLICA || COMBU...,PARA VENTA AL MERCADO LOCAL,Activo
4,RP202101000003D4,76169990,MINI SOPORTE DE TUBERIA MINI TRUSS BRACKET,201811028F,SONY,1312J01,No Aplica,Unidades,TURQUÍA,NaN,PARA VENTA AL MERCADO LOCAL,Activo
5,RP202006000006CB,94039090,TOPE PARA MESA DE EXTERIOR,1908DV08,EZPELETA,19DV01,NaN,Unidades,CHINA,MATERIAL: PLASTICO || DIMENSIONES: 80X80CM ||,PARA VENTA AL MERCADO LOCAL,Activo
6,RP202006000006CC,94039090,BASE PARA MESA DE EXTERIOR,1908DV08,EZPELETA,19DV01,NaN,Unidades,ESTADOS UNIDOS,MATERIAL: PLASTICO || DIMENSIONES: 80CM ||,PARA VENTA AL MERCADO LOCAL,Activo
7,RP202006000006CD,94039010,MESA CIRCULAR,1908DV42,CARMENES,19DV01,NaN,Unidades,ESPAÑA,MATERIAL: MADERA || DIMENSIONES: 50CM ||,PARA VENTA AL MERCADO LOCAL,Activo
8,RP20200600000637,21069092,SUPLEMENTO NUTRICIONAL EN CAPSULA,2006DV32,THERASCIENCE,20DV10,CETOLIKE MCT OIL,Litros,ESTADOS UNIDOS,PRESENTACION: 500 ML || SABOR: NO APLICA ||,PARA VENTA AL MERCADO LOCAL,Activo
9,RP202007000003E6,59090000,MANGUERA,20192911J03,AICONTROLLER,2911J01,No Aplica,Kilogramos,ESPAÑA,NaN,PRODUCTO DE ZONA FRANCA,Activo
10,RP20200800000058,39174000,CODO,2807MC002,LEHMAN PIPE & SUPPLY,0728MC002,NaN,Kilogramos,ESTADOS UNIDOS,DIAMETRONOMINAL: 4 || USO: ABASTECIMIENTO DE A...,PARA VENTA AL MERCADO LOCAL,Activo
11,RP20190600000323,94035000,PAX ARMARIO ROPERO 29X22X79,CL2017,IKEA,1905MC608,70141389,Unidades,ITALIA,NaN,PARA VENTA AL MERCADO LOCAL,Activo
12,RP20190900000D6E,94049000,ROSENDUN PROTECTOR COLCHON KING,CL2017,IKEA,CL1909-454,80260485,Unidades,CHINA,NaN,PARA VENTA AL MERCADO LOCAL,Activo
13,RP202003000009E9,94035000,BRIMNES ARMAZON CAMA+ALMACENAJECE KING BLANCO,CL2017,IKEA,20JR328,90250117,Unidades,ESTADOS UNIDOS,NaN,PARA VENTA AL MERCADO LOCAL,Activo
14,RP20200200000112,44123900,MADERA CONTRACHAPADA,1911DV39,PINO,19DV01,NO APLICA,Metros Cuadrados,ESTADOS UNIDOS,NaN,PARA VENTA AL MERCADO LOCAL,Activo
15,RP20191100001189,72162100,PERFILES EN L,1911JR774,KOCAER HADDECLIK SAN VE TIC A.S.,19JR774,NaN,Kilogramos,TURQUÍA,ALTURA: 150 MM || MATERIAL: DEMAS ACEROS ALEAD...,PARA VENTA AL MERCADO LOCAL,Activo
16,RP2020030000086D,72104910,BOBINA,1905F32,CARIBBEAN STEEL AND TUBE,19JR770,NaN,Kilogramos,REPÚBLICA DOMINICANA,MATERIAL: DEMAS ACEROS ALEADOS || ANCHURA: 121...,PARA VENTA AL MERCADO LOCAL,Activo
17,RP202003000007BA,72107010,BOBINA,2020JR69,INDOMAN,20JR69,NaN,Kilogramos,CHINA,MATERIAL: HIERRO O ACERO SIN ALEAR || ANCHURA:...,PARA VENTA AL MERCADO LOCAL,Activo
18,RP202003000007BB,72106110,BOBINA,2020JR69,INDOMAN,20JR69,NaN,Kilogramos,CHINA,MATERIAL: HIERRO O ACERO SIN ALEAR || ANCHURA:...,PARA VENTA AL MERCADO LOCAL,Activo
19,RP202003000007A5,72106110,BOBINA,2020JR69,INDOMAN,20JR69,NaN,Kilogramos,CHINA,MATERIAL: HIERRO O ACERO SIN ALEAR || ANCHURA:...,PARA VENTA AL MERCADO LOCAL,Activo
20,RP201810000000AD,22042100,VINO,2018100201DV,CHATEAU CANTIN,201810020102DV,SAINT EMILION GRAND CRU 16,Litros,FRANCIA,GRADOALCOHOL: 14.50 || UNIDADXCAJA: 6 || PRESE...,PARA VENTA AL MERCADO LOCAL,Activo
21,RP2018100000030C,87032499,AUTOMOVIL,B09110016,Mercedes Benz,M001071117,S560,Unidades,ALEMANIA,SERIE: NO APLICA || COMBUSTIBLE: GASOLINA || C...,PARA VENTA AL MERCADO LOCAL,Activo
22,20180600000DCA,22042100,VINO,201806220102,VERBO,2018062201C,AGLIANICO DEL VULTURE,Litros,ITALIA,GRADOALCOHOL: 14.00 || UNIDADXCAJA: 6 || PRESE...,PARA VENTA AL MERCADO LOCAL,Activo
23,201708000006C4,22087020,LICOR,2018092001DF,BROGANS,2018092002DF,IRISH CREAM,Litros,IRLANDA,GRADOALCOHOL: 40.00 || UNIDADXCAJA: 12 || PRES...,PARA VENTA AL MERCADO LOCAL,Activo
24,RP201903000006DB,21069092,SUPLEMENTO NUTRICIONAL EN CAPSULA,1903MC01,LIFE EXTENSION,19MC88,SUPER ABSORBABLE COQ10,Unidades,ESTADOS UNIDOS,PRESENTACION: 60UNIDADES || SABOR: NO APLICA ||,PARA VENTA AL MERCADO LOCAL,Activo

In [55]:
dates = datos[datos["Marca"]=="Mercedes Benz"]
dates

,Código de Producto,Partida Arancelaria,Nombre de Producto,Cod. Marca,Marca,Cod. Modelo,Modelo,Unidad,País,Especificaciones,Régimen,Estado
21,RP2018100000030C,87032499,AUTOMOVIL,B09110016,Mercedes Benz,M001071117,S560,Unidades,ALEMANIA,SERIE: NO APLICA || COMBUSTIBLE: GASOLINA || C...,PARA VENTA AL MERCADO LOCAL,Activo